export const evidenceAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_evidenceLedgerAddress",
        type: "address",
        internalType: "address",
      },
      { name: "_evidenceId", type: "bytes32", internalType: "bytes32" },
      { name: "_creator", type: "address", internalType: "address" },
      {
        name: "_initialOwner",
        type: "address",
        internalType: "address",
      },
      { name: "_description", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "discontinueEvidence",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getChainOfCustody",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Evidence.CustodyRecord[]",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          {
            name: "timestamp",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentOwnerTranfserTime",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEvidenceCreator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEvidenceDescription",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEvidenceId",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEvidenceState",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTimeOfCreation",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTimeOfDiscontinuation",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "EvindenceDiscontinued",
    inputs: [
      {
        name: "evidenceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "TIME_OF_DISCONTINUATION",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "Error_CallerIsNotCreator", inputs: [] },
  { type: "error", name: "Error_CallerIsNotCurrentOwner", inputs: [] },
  { type: "error", name: "Error_CreatorIsNotInitialOwner", inputs: [] },
  { type: "error", name: "Error_EvindenceDiscontinued", inputs: [] },
  { type: "error", name: "Error_UnauthorizedDeployment", inputs: [] },
];
